### ISSUE TITLE
Remote: Section 1 (in report section 6)

### ISSUE THREAD

**Issue by fecton** [fecton/khai-git-team-work#5]
https://learngitbranching.js.org/?locale=en_EN

![Image](https://github.com/fecton/khai-git-team-work/assets/76391547/2851a5bb-140d-4d52-9323-7c023855c292)

**Acceptance criteria:**
- [x] All tasks specified on the screenshot are completed
- [x] Report prepared in docx format
- [x] Report doesn't include a title page

Report contains:
- [x] Section header for example 3
- [x] Section contains screenshots numbered according to section ({section},{screenshot number}): 3.1, 3.2, 3.3
- [x] Each section had a conclusion

**Comment by awevstt** [comment]
[Git-Технологія3.docx](https://github.com/fecton/khai-git-team-work/files/14523475/Git-.3.docx)

**Comment by fecton** [comment]
Approved
